# site wide config and variables

title: Alex Pareto
email: alex@alexpareto.com
tagline: "@alexpareto"
description: >-
  Hey! My name's Alex. I work on engineering at NTWRK. I'm based in LA. 
  I write here mostly about software and startups. 
  Previously I founded Demeanor (Y Combinator S18) which was acquired by NTWRK in 2019. 
  Before that, I worked on the video platform at Facebook. I studied at USC and Andover.
baseurl: "/"
url: "https://alexpareto.com"
google_analytics: "UA-72564929-2"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
